### ISSUE TITLE
audit-argument-checks rule stopped working

### ISSUE THREAD

**Issue by rohithb** [dferber90/eslint-plugin-meteor#502] opened 2017-06-13 09:13 UTC
I'm using this plugin for past 5 to 6 months. And audit-argument-checks rule worked fine.
But recently few weeks back I noticed it stopped working. I tried adding 
`"meteor/audit-argument-checks": 2` in the rules of my `eslintrc.json`, but no success.
I tried re-installing the plugins then also its not working?

Atom version: `1.17.2 x64`

My devDependencies:
```
"devDependencies": {
    "babel-eslint": "^7.1.1",
    "chimp": "^0.47.2",
    "eslint": "^3.10.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-import-resolver-meteor": "^0.3.4",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-meteor": "^4.0.1",
    "eslint-plugin-react": "^6.7.1"
  }
```
eslintrc.json
```
{
  "parser": "babel-eslint",
  "parserOptions": {
    "allowImportExportEverywhere": true
  },
  "extends": [
    "airbnb",
    "plugin:meteor/recommended",
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  "plugins": [
    "jsx-a11y",
    "import",
    "meteor"
  ],
  "settings": {
    "import/resolver": "meteor"
  },
  "env": {
    "browser": true,
    "node": true
  },
  "rules": {
    "import/extensions": ["off", "never"],
    "import/no-extraneous-dependencies": "off",
    "import/prefer-default-export": "off",
    "no-var": "error",
    "import/no-absolute-path": "off",
    "meteor/template-names": [2, "camel-case"],
    "meteor/audit-argument-checks": 2
  }
}
```

**Comment by dferber90** [comment] 2017-06-13 09:27
Can you set up a small reproduction repository with minimal dependencies to reproduce the error?

**Comment by dferber90** [comment] 2017-07-24 07:35
Still works for me. Closing this. Please provide a reproduction repository in case you're still seeing the issue.

**Closed** 2017-07-24 07:38 UTC
